---
title: "What am I reading?"
output: 
  html_document:
    css: ['CSSBackgrounds.css', 'CSSFonts.css']
    includes:
      after_body: footer.html
---

### Hourglass Model for Developmental Evolution of Ant Castes. Tribble and Kronauer 2020.  
#### March 16, 2021
[My reading notes](https://docs.google.com/document/d/1LJFPfM0A7-sKwcERLotJq89o2nqhIciZiCuwJxRL1tk/edit?usp=sharing)

### Regulation, development, and evolution of caste ratios in the hyperdiverse ant genus Pheidole. Lillico-Ouachour and Abhouheif 2017.  
#### March 15, 2021
[My reading notes](https://docs.google.com/document/d/1FpGHzLePX8JOV1RXT2stKagY-hr7oVclLWGpUze1OQM/edit?usp=sharing)

### Lack of interruption of the gene network underlying wing polyphenism in an early-branching ant genus. Béhague et al. 2018.  
#### March 11, 2021
[My reading notes](https://docs.google.com/document/d/1YoztUYG9BUa4MpMllk9ZxuKsL8Pnz-87DvOnUSC4kvE/edit?usp=sharing)

### Evolution of social insect polyphenism facilitated by the sex differentiation cascade. Klein et al. 2016.  
#### March 10, 2021
[My reading notes](https://docs.google.com/document/d/1H9FZP9NpckxVQo8uAmyMoTp5TODqYbo9w2fNnZDUlmY/edit?usp=sharing)

### The evolution of worker caste diversity in social insects. Fjerdingstad & Crozier 2006.  
#### March 9, 2021
[My reading notes](https://docs.google.com/document/d/11sKpZP8iYssU4TrFOqeaa_w6OLcyH1UM4FbisTD9mdU/edit?usp=sharing)

### Soldier determination in ants: a new role for juvenile hormone. Wheeler & Nijhout 1981.  
#### March 5, 2021
[My reading notes](https://docs.google.com/document/d/1jqWpLmFYHR6GlRh5BapJ2hELbNeiwLSvOpwcMb8iNaM/edit?usp=sharing)

### A new interpretation of the frequency curves associated with ant polymorphism. Wilson 1954.
#### March 5, 2021
[My reading notes](https://docs.google.com/document/d/1GF2HsG5swRe48wXQa-BZwDl2_Jb7xfINAnutzdGy82k/edit?usp=sharing)

### The origin of wing polyphenism in ants: an eco-evo-devo perspective. Hannah & Abouheif 2021. 
#### March 3, 2021
[My reading notes](https://docs.google.com/document/d/1OaFCmt3hNOg_Od7MKyjCs1GvNaivHZqebXLPpi6FhWk/edit?usp=sharing)